const db = require('./db'); // Ajuste o caminho se necessário dependendo de onde o arquivo ficará

const characterCatalog = [
    // ==========================================
    // 🐉 DRAGON BALL CLÁSSICO & INÍCIO DBZ (1 - 50)
    // ==========================================
    { name: "Goku (Criança)", slug: "goku-crianca", rarity: "C", element: "Fisico", mult: 1.0 },
    { name: "Goku Oozaru", slug: "goku-oozaru", rarity: "U", element: "Fisico", mult: 1.4 },
    { name: "Bulma (Jovem)", slug: "bulma-jovem", rarity: "C", element: "Tecnologico", mult: 0.5 },
    { name: "Mestre Kame (Base)", slug: "kame-base", rarity: "C", element: "Fisico", mult: 1.1 },
    { name: "Mestre Kame (100% Poder)", slug: "kame-100", rarity: "U", element: "Energia", mult: 1.3 },
    { name: "Kuririn (Criança)", slug: "kuririn-crianca", rarity: "C", element: "Fisico", mult: 0.9 },
    { name: "Yamcha (Bandido do Deserto)", slug: "yamcha-bandido", rarity: "C", element: "Fisico", mult: 0.8 },
    { name: "Tenshinhan (Clássico)", slug: "tenshinhan-classico", rarity: "C", element: "Energia", mult: 1.2 },
    { name: "Chaos (Clássico)", slug: "chaos-classico", rarity: "C", element: "Magia", mult: 0.7 },
    { name: "Yajirobe", slug: "yajirobe", rarity: "C", element: "Fisico", mult: 0.9 },
    { name: "Tao Pai Pai", slug: "tao-pai-pai", rarity: "C", element: "Fisico", mult: 1.1 },
    { name: "Tao Pai Pai (Ciborgue)", slug: "tao-ciborgue", rarity: "U", element: "Tecnologico", mult: 1.3 },
    { name: "General Blue", slug: "general-blue", rarity: "C", element: "Magia", mult: 1.0 },
    { name: "Chefe Coelho", slug: "chefe-coelho", rarity: "C", element: "Magia", mult: 0.8 },
    { name: "Vovô Gohan", slug: "vovo-gohan", rarity: "U", element: "Fisico", mult: 1.3 },
    { name: "Piccolo Daimaoh (Velho)", slug: "daimaoh-velho", rarity: "U", element: "Trevas", mult: 1.3 },
    { name: "Piccolo Daimaoh (Jovem)", slug: "daimaoh-jovem", rarity: "R", element: "Trevas", mult: 1.6 },
    { name: "Tambourine", slug: "tambourine", rarity: "C", element: "Trevas", mult: 1.1 },
    { name: "Cymbal", slug: "cymbal", rarity: "C", element: "Trevas", mult: 1.0 },
    { name: "Kami-Sama", slug: "kami-sama", rarity: "U", element: "Divino", mult: 1.4 },
    { name: "Sr. Popo", slug: "sr-popo", rarity: "U", element: "Magia", mult: 1.5 },
    { name: "Piccolo Jr. (Torneio)", slug: "piccolo-jr", rarity: "R", element: "Energia", mult: 1.6 },
    { name: "Goku (Adolescente)", slug: "goku-adolescente", rarity: "R", element: "Fisico", mult: 1.6 },
    { name: "Chichi (Torneio)", slug: "chichi-torneio", rarity: "C", element: "Fisico", mult: 1.0 },
    { name: "Raditz", slug: "raditz", rarity: "U", element: "Energia", mult: 1.4 },
    { name: "Saibaman", slug: "saibaman", rarity: "C", element: "Natureza", mult: 1.1 },
    { name: "Nappa", slug: "nappa", rarity: "R", element: "Fisico", mult: 1.6 },
    { name: "Vegeta (Scouter)", slug: "vegeta-scouter", rarity: "R", element: "Energia", mult: 1.8 },
    { name: "Vegeta Oozaru", slug: "vegeta-oozaru", rarity: "S", element: "Fisico", mult: 2.0 },
    { name: "Goku (Base Z)", slug: "goku-base-z", rarity: "R", element: "Fisico", mult: 1.7 },
    { name: "Goku Kaioken x2", slug: "goku-kaioken-2", rarity: "R", element: "Energia", mult: 1.9 },
    { name: "Goku Kaioken x4", slug: "goku-kaioken-4", rarity: "S", element: "Energia", mult: 2.1 },
    { name: "Gohan (Criança Z)", slug: "gohan-crianca-z", rarity: "C", element: "Fisico", mult: 1.0 },
    { name: "Gohan Oozaru", slug: "gohan-oozaru", rarity: "U", element: "Fisico", mult: 1.5 },
    { name: "Kuririn (Careca Z)", slug: "kuririn-z", rarity: "U", element: "Energia", mult: 1.3 },
    { name: "Piccolo (Capa e Turbante)", slug: "piccolo-capa", rarity: "U", element: "Energia", mult: 1.5 },
    { name: "Tenshinhan (Z)", slug: "tenshinhan-z", rarity: "U", element: "Energia", mult: 1.3 },
    { name: "Yamcha (Z)", slug: "yamcha-z", rarity: "U", element: "Fisico", mult: 1.2 },
    { name: "Chaos (Z)", slug: "chaos-z", rarity: "C", element: "Magia", mult: 1.0 },
    { name: "Rei Cutelo", slug: "rei-cutelo", rarity: "C", element: "Fisico", mult: 0.9 },
    { name: "Launch (Loira)", slug: "launch-loira", rarity: "C", element: "Tecnologico", mult: 0.8 },
    { name: "Uranai Baba", slug: "uranai-baba", rarity: "C", element: "Magia", mult: 0.5 },
    { name: "Mumia (Torneio Uranai)", slug: "mumia", rarity: "C", element: "Trevas", mult: 0.7 },
    { name: "Akkuman", slug: "akkuman", rarity: "U", element: "Trevas", mult: 1.3 },
    { name: "Pilar Máquina", slug: "pilaf-maquina", rarity: "C", element: "Tecnologico", mult: 0.8 },
    { name: "Oolong (Morcego)", slug: "oolong-morcego", rarity: "C", element: "Magia", mult: 0.2 },
    { name: "Pual", slug: "pual", rarity: "C", element: "Magia", mult: 0.2 },
    { name: "Karin-Sama", slug: "karin", rarity: "C", element: "Divino", mult: 1.1 },
    { name: "Enma Daioh", slug: "enma-daioh", rarity: "U", element: "Divino", mult: 1.5 },
    { name: "Senhor Kaioh", slug: "senhor-kaioh", rarity: "U", element: "Divino", mult: 1.4 },

    // ==========================================
    // 🪐 SAGA NAMEKUSEI & FREEZA (51 - 100)
    // ==========================================
    { name: "Soldado de Freeza", slug: "soldado-freeza", rarity: "C", element: "Energia", mult: 0.9 },
    { name: "Appule", slug: "appule", rarity: "C", element: "Energia", mult: 1.0 },
    { name: "Cui", slug: "cui", rarity: "U", element: "Energia", mult: 1.4 },
    { name: "Dodoria", slug: "dodoria", rarity: "R", element: "Fisico", mult: 1.6 },
    { name: "Zarbon (Base)", slug: "zarbon-base", rarity: "R", element: "Energia", mult: 1.7 },
    { name: "Zarbon (Monstro)", slug: "zarbon-monstro", rarity: "R", element: "Fisico", mult: 1.8 },
    { name: "Gurdo", slug: "gurdo", rarity: "R", element: "Magia", mult: 1.6 },
    { name: "Rikum", slug: "rikum", rarity: "S", element: "Fisico", mult: 2.0 },
    { name: "Boter", slug: "boter", rarity: "S", element: "Vento", mult: 2.0 },
    { name: "Yuz", slug: "yuz", rarity: "S", element: "Energia", mult: 2.0 },
    { name: "Capitão Ginyu", slug: "capitao-ginyu", rarity: "S", element: "Energia", mult: 2.2 },
    { name: "Ginyu (Corpo do Goku)", slug: "ginyu-goku", rarity: "S", element: "Fisico", mult: 2.1 },
    { name: "Ginyu (Sapo)", slug: "ginyu-sapo", rarity: "C", element: "Natureza", mult: 0.1 },
    { name: "Nail", slug: "nail", rarity: "S", element: "Energia", mult: 2.0 },
    { name: "Dende", slug: "dende", rarity: "C", element: "Magia", mult: 0.5 },
    { name: "Grande Patriarca", slug: "grande-patriarca", rarity: "C", element: "Magia", mult: 0.3 },
    { name: "Vegeta (Armadura Namek)", slug: "vegeta-namek", rarity: "S", element: "Energia", mult: 2.1 },
    { name: "Vegeta (Zenkai Namek)", slug: "vegeta-zenkai", rarity: "S", element: "Energia", mult: 2.4 },
    { name: "Gohan (Potencial Desbloqueado)", slug: "gohan-potencial-namek", rarity: "S", element: "Energia", mult: 2.0 },
    { name: "Kuririn (Potencial Desbloqueado)", slug: "kuririn-potencial", rarity: "R", element: "Energia", mult: 1.8 },
    { name: "Piccolo (Fundido com Nail)", slug: "piccolo-nail", rarity: "S", element: "Fisico", mult: 2.3 },
    { name: "Goku (Chegada em Namek)", slug: "goku-namek", rarity: "S", element: "Fisico", mult: 2.2 },
    { name: "Goku Kaioken x10", slug: "goku-kaioken-10", rarity: "S", element: "Energia", mult: 2.4 },
    { name: "Goku Kaioken x20", slug: "goku-kaioken-20", rarity: "SS", element: "Energia", mult: 2.6 },
    { name: "Freeza (1ª Forma)", slug: "freeza-1", rarity: "S", element: "Trevas", mult: 2.2 },
    { name: "Freeza (2ª Forma)", slug: "freeza-2", rarity: "S", element: "Fisico", mult: 2.3 },
    { name: "Freeza (3ª Forma)", slug: "freeza-3", rarity: "S", element: "Energia", mult: 2.4 },
    { name: "Freeza (Forma Final)", slug: "freeza-final", rarity: "SS", element: "Trevas", mult: 2.7 },
    { name: "Freeza (100% Poder)", slug: "freeza-100", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Goku Super Saiyajin (Namek)", slug: "goku-ssj-namek", rarity: "SSS", element: "Luz", mult: 3.0 },
    { name: "Rei Cold", slug: "rei-cold", rarity: "SS", element: "Trevas", mult: 2.6 },
    { name: "Mecha Freeza", slug: "mecha-freeza", rarity: "SS", element: "Tecnologico", mult: 2.8 },
    { name: "Bardock (Base)", slug: "bardock-base", rarity: "R", element: "Fisico", mult: 1.7 },
    { name: "Bardock (Fita Ensanguentada)", slug: "bardock-fita", rarity: "S", element: "Energia", mult: 2.0 },
    { name: "Bardock Super Saiyajin", slug: "bardock-ssj", rarity: "SS", element: "Luz", mult: 2.7 },
    { name: "Chilled", slug: "chilled", rarity: "S", element: "Trevas", mult: 2.0 },
    { name: "Gohan (Corte de Tigela)", slug: "gohan-tigela", rarity: "U", element: "Fisico", mult: 1.5 },
    { name: "Vegeta (Camisa Rosa)", slug: "vegeta-badman", rarity: "U", element: "Fisico", mult: 1.5 },
    { name: "Trunks do Futuro (Base)", slug: "trunks-futuro-base", rarity: "S", element: "Fisico", mult: 2.2 },
    { name: "Trunks do Futuro Super Saiyajin", slug: "trunks-futuro-ssj", rarity: "SSS", element: "Luz", mult: 3.1 },
    { name: "Goku (Traje Yadrat)", slug: "goku-yadrat", rarity: "SSS", element: "Luz", mult: 3.1 },
    { name: "Garlic Jr. (Base)", slug: "garlic-jr", rarity: "R", element: "Trevas", mult: 1.8 },
    { name: "Garlic Jr. (Super Forma)", slug: "garlic-jr-super", rarity: "S", element: "Fisico", mult: 2.1 },
    { name: "Spice", slug: "spice", rarity: "U", element: "Energia", mult: 1.4 },
    { name: "Vinegar", slug: "vinegar", rarity: "U", element: "Fisico", mult: 1.4 },
    { name: "Mustard", slug: "mustard", rarity: "U", element: "Fisico", mult: 1.4 },
    { name: "Salt", slug: "salt", rarity: "U", element: "Energia", mult: 1.4 },
    { name: "Turles", slug: "turles", rarity: "S", element: "Trevas", mult: 2.2 },
    { name: "Senhor Enma (Fruto da Árvore)", slug: "turles-fruto", rarity: "SS", element: "Trevas", mult: 2.5 },
    { name: "Lord Slug", slug: "lord-slug", rarity: "S", element: "Trevas", mult: 2.2 },

    // ==========================================
    // 🧬 SAGA ANDROIDES E CELL (101 - 150)
    // ==========================================
    { name: "Androide 19", slug: "androide-19", rarity: "S", element: "Tecnologico", mult: 2.2 },
    { name: "Androide 20 (Dr. Gero)", slug: "androide-20", rarity: "S", element: "Tecnologico", mult: 2.3 },
    { name: "Vegeta Super Saiyajin", slug: "vegeta-ssj", rarity: "SSS", element: "Luz", mult: 3.2 },
    { name: "Goku (Doença do Coração)", slug: "goku-doenca", rarity: "S", element: "Fisico", mult: 2.0 },
    { name: "Androide 17", slug: "androide-17-z", rarity: "SS", element: "Tecnologico", mult: 2.7 },
    { name: "Androide 18", slug: "androide-18-z", rarity: "SS", element: "Tecnologico", mult: 2.7 },
    { name: "Androide 16", slug: "androide-16", rarity: "SS", element: "Fisico", mult: 2.9 },
    { name: "Piccolo (Fundido com Kami-Sama)", slug: "piccolo-kami", rarity: "SS", element: "Energia", mult: 2.8 },
    { name: "Cell (Imperfeito)", slug: "cell-imperfeito", rarity: "SS", element: "Natureza", mult: 2.9 },
    { name: "Cell (Semi-Perfeito)", slug: "cell-semi", rarity: "SSS", element: "Fisico", mult: 3.3 },
    { name: "Cell (Perfeito)", slug: "cell-perfeito", rarity: "SSS", element: "Energia", mult: 3.6 },
    { name: "Super Vegeta", slug: "super-vegeta", rarity: "SSS", element: "Fisico", mult: 3.4 },
    { name: "Super Trunks", slug: "super-trunks", rarity: "SSS", element: "Fisico", mult: 3.4 },
    { name: "Trunks (Ultra SSJ - Grau 3)", slug: "trunks-ultra", rarity: "SSS", element: "Fisico", mult: 3.5 },
    { name: "Goku (Super Saiyajin Full Power)", slug: "goku-ssj-full", rarity: "SSS", element: "Luz", mult: 3.5 },
    { name: "Gohan (Super Saiyajin)", slug: "gohan-ssj-cell", rarity: "SSS", element: "Luz", mult: 3.4 },
    { name: "Cell Jr.", slug: "cell-jr", rarity: "SS", element: "Energia", mult: 2.8 },
    { name: "Gohan Super Saiyajin 2 (Jovem)", slug: "gohan-ssj2-jovem", rarity: "UR", element: "Luz", mult: 4.2 },
    { name: "Cell (Super Perfeito)", slug: "cell-super-perfeito", rarity: "UR", element: "Trevas", mult: 4.0 },
    { name: "Goku (Anjo)", slug: "goku-anjo-cell", rarity: "SSS", element: "Luz", mult: 3.5 },
    { name: "Trunks do Futuro (Cabelo Curto)", slug: "trunks-futuro-curto", rarity: "SSS", element: "Fisico", mult: 3.2 },
    { name: "Mr. Satan", slug: "mr-satan", rarity: "C", element: "Fisico", mult: 0.5 },
    { name: "Androide 13", slug: "androide-13", rarity: "SS", element: "Tecnologico", mult: 2.7 },
    { name: "Super Androide 13", slug: "super-13", rarity: "SSS", element: "Fisico", mult: 3.2 },
    { name: "Androide 14", slug: "androide-14", rarity: "S", element: "Fisico", mult: 2.2 },
    { name: "Androide 15", slug: "androide-15", rarity: "S", element: "Tecnologico", mult: 2.2 },
    { name: "Bojack (Base)", slug: "bojack-base", rarity: "SSS", element: "Trevas", mult: 3.1 },
    { name: "Bojack (Poder Total)", slug: "bojack-full", rarity: "SSS", element: "Trevas", mult: 3.5 },
    { name: "Zangya", slug: "zangya", rarity: "SS", element: "Energia", mult: 2.6 },
    { name: "Kogu", slug: "kogu", rarity: "S", element: "Fisico", mult: 2.4 },
    { name: "Bido", slug: "bido", rarity: "S", element: "Fisico", mult: 2.4 },
    { name: "Bujin", slug: "bujin", rarity: "S", element: "Magia", mult: 2.4 },
    { name: "Broly (Base Z)", slug: "broly-base-z", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Broly (Super Saiyajin Z)", slug: "broly-ssj-z", rarity: "SSS", element: "Energia", mult: 3.3 },
    { name: "Broly (Lendário SSJ Z)", slug: "broly-lssj-z", rarity: "UR", element: "Trevas", mult: 4.1 },
    { name: "Goku (Absorção da Genki Dama)", slug: "goku-genki-dama", rarity: "UR", element: "Energia", mult: 4.0 },
    { name: "Cooler (Base)", slug: "cooler-base", rarity: "SS", element: "Trevas", mult: 2.5 },
    { name: "Cooler (Forma Final)", slug: "cooler-final", rarity: "SSS", element: "Fisico", mult: 3.0 },
    { name: "Metal Cooler", slug: "metal-cooler", rarity: "SSS", element: "Tecnologico", mult: 3.2 },
    { name: "Metal Cooler (Núcleo)", slug: "metal-cooler-core", rarity: "UR", element: "Tecnologico", mult: 4.0 },
    { name: "Neiz", slug: "neiz", rarity: "S", element: "Energia", mult: 2.0 },
    { name: "Dore", slug: "dore", rarity: "S", element: "Fisico", mult: 2.0 },
    { name: "Salza", slug: "salza", rarity: "S", element: "Energia", mult: 2.1 },
    { name: "Paikuhan", slug: "paikuhan", rarity: "SSS", element: "Fisico", mult: 3.3 },
    { name: "Olibu", slug: "olibu", rarity: "SS", element: "Fisico", mult: 2.5 },
    { name: "Rei Kaioh do Grande Senhor", slug: "grande-sr-kaioh", rarity: "SS", element: "Divino", mult: 2.5 },
    { name: "Gohan (Adolescente Jaqueta)", slug: "gohan-jaqueta", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Trunks do Futuro (Cabelo Longo)", slug: "trunks-longo", rarity: "SSS", element: "Fisico", mult: 3.1 },
    { name: "Cell (Casulo)", slug: "cell-casulo", rarity: "C", element: "Natureza", mult: 0.1 },
    { name: "Trunks (Bebê)", slug: "trunks-bebe", rarity: "C", element: "Fisico", mult: 0.1 },

    // ==========================================
    // 🍬 SAGA MAJIN BOO (151 - 200)
    // ==========================================
    { name: "Gohan (Adulto Base)", slug: "gohan-adulto", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Grande Saiyaman", slug: "grande-saiyaman", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Gohan Super Saiyajin (Adulto)", slug: "gohan-ssj-adulto", rarity: "SSS", element: "Luz", mult: 3.2 },
    { name: "Gohan Super Saiyajin 2 (Adulto)", slug: "gohan-ssj2-adulto", rarity: "SSS", element: "Luz", mult: 3.5 },
    { name: "Goten (Base)", slug: "goten-base", rarity: "S", element: "Fisico", mult: 2.3 },
    { name: "Goten Super Saiyajin", slug: "goten-ssj", rarity: "SS", element: "Luz", mult: 2.7 },
    { name: "Trunks Criança (Base)", slug: "trunks-kid-base", rarity: "S", element: "Fisico", mult: 2.4 },
    { name: "Trunks Criança Super Saiyajin", slug: "trunks-kid-ssj", rarity: "SS", element: "Luz", mult: 2.8 },
    { name: "Videl (Base)", slug: "videl", rarity: "U", element: "Fisico", mult: 1.2 },
    { name: "Grande Saiyaman 2", slug: "saiyaman-2", rarity: "U", element: "Fisico", mult: 1.3 },
    { name: "Kaioshin do Leste (Shin)", slug: "shin", rarity: "SS", element: "Divino", mult: 2.9 },
    { name: "Kibito", slug: "kibito", rarity: "S", element: "Divino", mult: 2.4 },
    { name: "Kibitoshin", slug: "kibitoshin", rarity: "SSS", element: "Divino", mult: 3.4 },
    { name: "Spopovich", slug: "spopovich", rarity: "R", element: "Trevas", mult: 1.8 },
    { name: "Yamu", slug: "yamu", rarity: "R", element: "Trevas", mult: 1.7 },
    { name: "Babidi", slug: "babidi", rarity: "U", element: "Magia", mult: 1.5 },
    { name: "Pui Pui", slug: "pui-pui", rarity: "S", element: "Fisico", mult: 2.1 },
    { name: "Yakon", slug: "yakon", rarity: "S", element: "Trevas", mult: 2.3 },
    { name: "Dabura", slug: "dabura", rarity: "SSS", element: "Trevas", mult: 3.4 },
    { name: "Majin Vegeta", slug: "majin-vegeta", rarity: "UR", element: "Trevas", mult: 4.1 },
    { name: "Goku Super Saiyajin 2", slug: "goku-ssj2", rarity: "UR", element: "Luz", mult: 4.0 },
    { name: "Goku Super Saiyajin 3", slug: "goku-ssj3", rarity: "UR", element: "Luz", mult: 4.5 },
    { name: "Majin Boo (Gordo)", slug: "majin-boo-gordo", rarity: "UR", element: "Magia", mult: 4.2 },
    { name: "Boo (Maldade Pura)", slug: "boo-maldade", rarity: "UR", element: "Trevas", mult: 4.1 },
    { name: "Super Boo", slug: "super-boo", rarity: "UR", element: "Trevas", mult: 4.6 },
    { name: "Gotenks (Base)", slug: "gotenks-base", rarity: "SSS", element: "Fisico", mult: 3.6 },
    { name: "Gotenks Super Saiyajin", slug: "gotenks-ssj", rarity: "UR", element: "Luz", mult: 4.1 },
    { name: "Gotenks Super Saiyajin 3", slug: "gotenks-ssj3", rarity: "UR", element: "Luz", mult: 4.7 },
    { name: "Super Boo (Gotenks Absorvido)", slug: "buutenks", rarity: "LR", element: "Trevas", mult: 5.2 },
    { name: "Gohan Místico (Ultimate)", slug: "ultimate-gohan", rarity: "LR", element: "Fisico", mult: 5.0 },
    { name: "Super Boo (Gohan Absorvido)", slug: "buuhan", rarity: "LR", element: "Trevas", mult: 5.5 },
    { name: "Vegetto (Base)", slug: "vegetto-base", rarity: "UR", element: "Luz", mult: 4.8 },
    { name: "Super Vegetto", slug: "super-vegetto", rarity: "LR", element: "Luz", mult: 5.8 },
    { name: "Kid Boo", slug: "kid-boo", rarity: "LR", element: "Trevas", mult: 5.3 },
    { name: "Goku (Super Genki Dama)", slug: "goku-genki-boo", rarity: "LR", element: "Energia", mult: 5.6 },
    { name: "Uub (Criança)", slug: "uub-crianca", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Goku (Fim de Z)", slug: "goku-fim-z", rarity: "UR", element: "Fisico", mult: 4.1 },
    { name: "Janemba (Gordo)", slug: "janemba-gordo", rarity: "UR", element: "Magia", mult: 4.4 },
    { name: "Super Janemba", slug: "super-janemba", rarity: "LR", element: "Trevas", mult: 5.4 },
    { name: "Gogeta Super Saiyajin (Z)", slug: "gogeta-ssj-z", rarity: "LR", element: "Luz", mult: 5.7 },
    { name: "Tapion", slug: "tapion", rarity: "SSS", element: "Magia", mult: 3.2 },
    { name: "Hirudegarn (Metade)", slug: "hirudegarn-metade", rarity: "UR", element: "Trevas", mult: 4.1 },
    { name: "Hirudegarn (Completo)", slug: "hirudegarn", rarity: "LR", element: "Trevas", mult: 5.0 },
    { name: "Goku (Golpe do Dragão)", slug: "goku-ryuken", rarity: "LR", element: "Energia", mult: 5.2 },
    { name: "Rou Kaioshin (Antigo)", slug: "rou-kaioshin", rarity: "S", element: "Magia", mult: 2.0 },
    { name: "Vegeta (Anjo)", slug: "vegeta-anjo", rarity: "UR", element: "Luz", mult: 4.0 },
    { name: "VeKu (Fusão Falha)", slug: "veku", rarity: "C", element: "Fisico", mult: 0.5 },
    { name: "Gogeta Magro (Falha)", slug: "gogeta-magro", rarity: "C", element: "Fisico", mult: 0.5 },
    { name: "Gotenks Gordo (Falha)", slug: "gotenks-gordo", rarity: "C", element: "Fisico", mult: 0.4 },
    { name: "Gotenks Magro (Falha)", slug: "gotenks-magro", rarity: "C", element: "Fisico", mult: 0.4 },

    // ==========================================
    // 🌟 DRAGON BALL SUPER (Deuses & U6) (201 - 240)
    // ==========================================
    { name: "Bills, o Deus da Destruição", slug: "bills", rarity: "Godly", element: "Divino", mult: 8.5 },
    { name: "Whis", slug: "whis", rarity: "Godly", element: "Divino", mult: 9.5 },
    { name: "Goku Deus Super Saiyajin", slug: "goku-god", rarity: "LR", element: "Divino", mult: 6.0 },
    { name: "Vegeta (Fúria por Bulma)", slug: "vegeta-furia", rarity: "UR", element: "Fisico", mult: 4.8 },
    { name: "Freeza (Renascido)", slug: "freeza-renascido", rarity: "UR", element: "Trevas", mult: 4.5 },
    { name: "Freeza Dourado (Golden)", slug: "golden-freeza", rarity: "LR", element: "Luz", mult: 6.2 },
    { name: "Goku Super Saiyajin Blue", slug: "goku-blue", rarity: "LR", element: "Divino", mult: 6.5 },
    { name: "Vegeta Super Saiyajin Blue", slug: "vegeta-blue", rarity: "LR", element: "Divino", mult: 6.5 },
    { name: "Sorbet", slug: "sorbet", rarity: "U", element: "Tecnologico", mult: 1.5 },
    { name: "Tagoma", slug: "tagoma", rarity: "SS", element: "Fisico", mult: 2.8 },
    { name: "Shisami", slug: "shisami", rarity: "S", element: "Fisico", mult: 2.4 },
    { name: "Champa", slug: "champa", rarity: "Godly", element: "Divino", mult: 8.4 },
    { name: "Vados", slug: "vados", rarity: "Godly", element: "Divino", mult: 9.6 },
    { name: "Botamo", slug: "botamo", rarity: "SSS", element: "Fisico", mult: 3.5 },
    { name: "Magetta", slug: "magetta", rarity: "UR", element: "Fogo", mult: 4.1 },
    { name: "Frost (1ª Forma)", slug: "frost-1", rarity: "SSS", element: "Energia", mult: 3.4 },
    { name: "Frost (Forma Final)", slug: "frost-final", rarity: "UR", element: "Fisico", mult: 4.2 },
    { name: "Kyabe (Base)", slug: "kyabe-base", rarity: "SSS", element: "Fisico", mult: 3.8 },
    { name: "Kyabe Super Saiyajin", slug: "kyabe-ssj", rarity: "UR", element: "Luz", mult: 4.3 },
    { name: "Hit (Assassino)", slug: "hit", rarity: "LR", element: "Trevas", mult: 6.4 },
    { name: "Goku Blue Kaioken x10", slug: "goku-blue-kk10", rarity: "LR", element: "Energia", mult: 6.8 },
    { name: "Monaka", slug: "monaka", rarity: "C", element: "Fisico", mult: 0.1 },
    { name: "Goku Black (Base)", slug: "goku-black-base", rarity: "LR", element: "Trevas", mult: 6.1 },
    { name: "Goku Black Super Saiyajin Rosé", slug: "black-rose", rarity: "LR", element: "Trevas", mult: 6.6 },
    { name: "Zamasu (Futuro)", slug: "zamasu-futuro", rarity: "UR", element: "Divino", mult: 4.9 },
    { name: "Zamasu Gattai (Fusão)", slug: "zamasu-gattai", rarity: "LR", element: "Divino", mult: 7.0 },
    { name: "Zamasu Gattai (Corrompido)", slug: "zamasu-corrompido", rarity: "LR", element: "Trevas", mult: 7.3 },
    { name: "Trunks (Super Saiyajin Rage)", slug: "trunks-rage", rarity: "LR", element: "Luz", mult: 6.5 },
    { name: "Vegetto Blue", slug: "vegetto-blue", rarity: "Godly", element: "Divino", mult: 8.2 },
    { name: "Zamasu Infinito", slug: "zamasu-infinito", rarity: "Godly", element: "Trevas", mult: 8.5 },
    { name: "Zeno-Sama", slug: "zeno", rarity: "Godly", element: "Divino", mult: 10.0 },
    { name: "Zeno-Sama do Futuro", slug: "zeno-futuro", rarity: "Godly", element: "Divino", mult: 10.0 },
    { name: "Daishinkan (Sumo Sacerdote)", slug: "daishinkan", rarity: "Godly", element: "Divino", mult: 9.9 },
    { name: "Gowasu", slug: "gowasu", rarity: "SSS", element: "Divino", mult: 3.5 },
    { name: "Vegeta Deus Super Saiyajin", slug: "vegeta-god", rarity: "LR", element: "Divino", mult: 6.0 },
    { name: "Trunks (Espada Genki Dama)", slug: "trunks-espada-genki", rarity: "LR", element: "Luz", mult: 6.8 },
    { name: "Mai do Futuro", slug: "mai-futuro", rarity: "C", element: "Tecnologico", mult: 0.8 },
    { name: "Yajirobe do Futuro", slug: "yajirobe-futuro", rarity: "C", element: "Fisico", mult: 0.9 },
    { name: "Zuno", slug: "zuno", rarity: "U", element: "Magia", mult: 1.0 },
    { name: "Watagash", slug: "watagash", rarity: "U", element: "Trevas", mult: 1.5 },

    // ==========================================
    // ⚔️ TORNEIO DO PODER & FILMES SUPER (241 - 280)
    // ==========================================
    { name: "Bergamo", slug: "bergamo", rarity: "UR", element: "Fisico", mult: 4.5 },
    { name: "Basil", slug: "basil", rarity: "SSS", element: "Fogo", mult: 3.8 },
    { name: "Lavender", slug: "lavender", rarity: "SSS", element: "Trevas", mult: 3.8 },
    { name: "Toppo (Base)", slug: "toppo-base", rarity: "LR", element: "Fisico", mult: 6.4 },
    { name: "Toppo (Hakaishin)", slug: "toppo-hakaishin", rarity: "Godly", element: "Divino", mult: 8.0 },
    { name: "Dyspo", slug: "dyspo", rarity: "LR", element: "Vento", mult: 6.2 },
    { name: "Jiren (Base)", slug: "jiren-base", rarity: "Godly", element: "Fisico", mult: 8.5 },
    { name: "Jiren (Poder Total)", slug: "jiren-full", rarity: "Godly", element: "Fogo", mult: 9.0 },
    { name: "Caulifla (Base)", slug: "caulifla-base", rarity: "UR", element: "Fisico", mult: 4.3 },
    { name: "Caulifla Super Saiyajin 2", slug: "caulifla-ssj2", rarity: "LR", element: "Luz", mult: 5.5 },
    { name: "Kale (Base)", slug: "kale-base", rarity: "SSS", element: "Fisico", mult: 3.9 },
    { name: "Kale (Berserk)", slug: "kale-berserk", rarity: "LR", element: "Trevas", mult: 6.1 },
    { name: "Kale (Controlada)", slug: "kale-control", rarity: "LR", element: "Energia", mult: 5.8 },
    { name: "Kefla (Base)", slug: "kefla-base", rarity: "LR", element: "Fisico", mult: 6.3 },
    { name: "Kefla Super Saiyajin 2", slug: "kefla-ssj2", rarity: "LR", element: "Energia", mult: 7.1 },
    { name: "Ribrianne", slug: "ribrianne", rarity: "UR", element: "Magia", mult: 4.9 },
    { name: "Kakunsa", slug: "kakunsa", rarity: "UR", element: "Fisico", mult: 4.4 },
    { name: "Roasie", slug: "roasie", rarity: "UR", element: "Energia", mult: 4.4 },
    { name: "Anilaza", slug: "anilaza", rarity: "LR", element: "Tecnologico", mult: 6.7 },
    { name: "Saonel", slug: "saonel", rarity: "UR", element: "Fisico", mult: 4.5 },
    { name: "Pirina", slug: "pirina", rarity: "UR", element: "Energia", mult: 4.5 },
    { name: "Obni", slug: "obni", rarity: "UR", element: "Fisico", mult: 4.6 },
    { name: "Mestre Kame (Instinto)", slug: "kame-instinto", rarity: "UR", element: "Fisico", mult: 4.7 },
    { name: "Goku (Instinto Superior Incompleto)", slug: "goku-ui-omen", rarity: "Godly", element: "Divino", mult: 8.2 },
    { name: "Goku (Instinto Superior Completo)", slug: "goku-mui", rarity: "Godly", element: "Divino", mult: 9.3 },
    { name: "Vegeta Blue Evolution", slug: "vegeta-blue-evo", rarity: "Godly", element: "Luz", mult: 8.1 },
    { name: "Androide 17 (ToP)", slug: "androide-17-top", rarity: "LR", element: "Tecnologico", mult: 6.3 },
    { name: "Broly (Base Super)", slug: "broly-base-super", rarity: "LR", element: "Fisico", mult: 6.0 },
    { name: "Broly (Ikari/Fúria)", slug: "broly-ikari", rarity: "LR", element: "Trevas", mult: 6.8 },
    { name: "Broly Super Saiyajin (Super)", slug: "broly-ssj-super", rarity: "Godly", element: "Energia", mult: 8.0 },
    { name: "Broly (Poder Total Super)", slug: "broly-full-super", rarity: "Godly", element: "Fisico", mult: 8.8 },
    { name: "Gogeta (Base Super)", slug: "gogeta-base-super", rarity: "LR", element: "Fisico", mult: 6.5 },
    { name: "Gogeta Super Saiyajin (Super)", slug: "gogeta-ssj-super", rarity: "LR", element: "Luz", mult: 7.2 },
    { name: "Gogeta Blue", slug: "gogeta-blue", rarity: "Godly", element: "Divino", mult: 9.1 },
    { name: "Paragus (Super)", slug: "paragus-super", rarity: "C", element: "Tecnologico", mult: 0.8 },
    { name: "Cheelai", slug: "cheelai", rarity: "C", element: "Tecnologico", mult: 0.7 },
    { name: "Lemo", slug: "lemo", rarity: "C", element: "Tecnologico", mult: 0.6 },
    { name: "Gohan (Beast)", slug: "gohan-beast", rarity: "Godly", element: "Fisico", mult: 9.2 },
    { name: "Piccolo (Laranja)", slug: "orange-piccolo", rarity: "Godly", element: "Fisico", mult: 8.7 },
    { name: "Cell Max", slug: "cell-max", rarity: "Godly", element: "Tecnologico", mult: 8.9 },

    // ==========================================
    // 📖 MANGÁ (Moro & Granolah) + GT (281 - 300)
    // ==========================================
    { name: "Moro (Bode Velho)", slug: "moro-velho", rarity: "LR", element: "Magia", mult: 6.7 },
    { name: "Moro (Jovem Prime)", slug: "moro-prime", rarity: "Godly", element: "Magia", mult: 8.3 },
    { name: "Moro (73 Absorvido)", slug: "moro-73", rarity: "Godly", element: "Trevas", mult: 8.8 },
    { name: "Moro (Anjo Absorvido)", slug: "moro-anjo", rarity: "Godly", element: "Divino", mult: 9.4 },
    { name: "Merus (Patrulheiro)", slug: "merus", rarity: "LR", element: "Tecnologico", mult: 6.5 },
    { name: "Merus (Anjo)", slug: "merus-anjo", rarity: "Godly", element: "Divino", mult: 8.9 },
    { name: "Sete-Três (73)", slug: "sete-tres", rarity: "LR", element: "Tecnologico", mult: 5.9 },
    { name: "Saganbo", slug: "saganbo", rarity: "LR", element: "Fisico", mult: 6.2 },
    { name: "Granolah (Base)", slug: "granolah-base", rarity: "LR", element: "Fisico", mult: 6.8 },
    { name: "Granolah (Mais Forte do Universo)", slug: "granolah-full", rarity: "Godly", element: "Energia", mult: 8.6 },
    { name: "Gas (Base)", slug: "gas-base", rarity: "LR", element: "Magia", mult: 6.6 },
    { name: "Gas (Instinto Desperto)", slug: "gas-instinto", rarity: "Godly", element: "Trevas", mult: 8.8 },
    { name: "Gas (Velho/Zumbi)", slug: "gas-zumbi", rarity: "Godly", element: "Fisico", mult: 9.1 },
    { name: "Vegeta (Ultra Ego)", slug: "vegeta-ultra-ego", rarity: "Godly", element: "Trevas", mult: 9.2 },
    { name: "Black Freeza", slug: "black-freeza", rarity: "Godly", element: "Trevas", mult: 9.8 },
    { name: "Goku (True Ultra Instinct)", slug: "goku-true-ui", rarity: "Godly", element: "Divino", mult: 9.4 },
    { name: "Goku Super Saiyajin 4", slug: "goku-ssj4", rarity: "LR", element: "Fogo", mult: 7.2 },
    { name: "Vegeta Super Saiyajin 4", slug: "vegeta-ssj4", rarity: "LR", element: "Fogo", mult: 7.1 },
    { name: "Gogeta Super Saiyajin 4", slug: "gogeta-ssj4", rarity: "Godly", element: "Fisico", mult: 8.8 },
    { name: "Omega Shenron", slug: "omega-shenron", rarity: "Godly", element: "Trevas", mult: 8.6 }
];

function seedGacha() {
    console.log('[Gacha Seed] Iniciando o povoamento de 300 personagens de DragonVerse...');

    // Verifica quantos já existem para não inserir repetido atoa
    const countQuery = db.prepare('SELECT COUNT(*) as count FROM character_catalog').get();
    
    if (countQuery.count >= 300) {
        console.log('[Gacha Seed] O banco de dados já possui todos os guerreiros.');
        return;
    }

    const insert = db.prepare(`
        INSERT OR IGNORE INTO character_catalog (name, slug, rarity, element, base_damage_mult)
        VALUES (?, ?, ?, ?, ?)
    `);

    const transaction = db.transaction((chars) => {
        for (const char of chars) {
            insert.run(char.name, char.slug, char.rarity, char.element, char.mult);
        }
    });

    try {
        transaction(characterCatalog);
        console.log(`[Gacha Seed] ✅ Sucesso! Foram inseridos ${characterCatalog.length} personagens lendários na base.`);
    } catch (error) {
        console.error('[Gacha Seed] ❌ Erro ao povoar os personagens:', error);
    }
}

module.exports = { seedGacha, characterCatalog };
