function getBrazilDateTime() {
  const now = new Date();

  const date = now.toLocaleDateString('pt-BR', {
    timeZone: 'America/Campo_Grande',
  });

  const time = now.toLocaleTimeString('pt-BR', {
    timeZone: 'America/Campo_Grande',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  return { date, time };
}

async function helpCommand(message) {
  const { date, time } = getBrazilDateTime();

  await message.reply([
    '╭━━⪩ 🐉 *DRAGONVERSE BOT* ⪨━━',
    '▢',
    '▢ • *RPG:* DragonVerse',
    `▢ • *Data:* ${date}`,
    `▢ • *Hora:* ${time}`,
    '▢ • *Prefixo:* /',
    '▢ • *Versão:* 1.5.0',
    '▢ • *Menu:* /menu',
    '▢',
    '╰━━─「🪐」─━━',
    '',

    '╭━━⪩ 👤 *REGISTRO & PERFIL* ⪨━━',
    '▢',
    '▢ • */Personagens Nº*',
    '▢   ⤷ Mostra a lista de personagens do universo do numero.',
    '▢',
    '▢ • */Registro 2 PP*',
    '▢   ⤷ Registra um personagem livre.',
    '▢',
    '▢ • */Registro 2 PPBLOCK CÓDIGO*',
    '▢   ⤷ Registra personagem bloqueado com código.',
    '▢',
    '▢ • */Trocarpersonagem PP*',
    '▢   ⤷ Troca seu personagem por outro livre.',
    '▢   ⤷ Custo: 25% dos seus Zenies.',
    '▢',
    '▢ • */Perfil*',
    '▢   ⤷ Mostra personagem, Ki, Zenies, cargo e trabalho.',
    '▢',
    '▢ • */meuid*',
    '▢   ⤷ Mostra seu JID/LID para virar admin.',
    '▢',
    '╰━━─「👤」─━━',
    '',

    '╭━━⪩ 💰 *ECONOMIA & BANCO* ⪨━━',
    '▢',
    '▢ • */depositar valor*',
    '▢   ⤷ Deposita Zenies no banco.',
    '▢   ⤷ Rende 25% a cada 4 dias.',
    '▢',
    '▢ • */pix @pessoa valor*',
    '▢   ⤷ Transfere Zenies para outro jogador.',
    '▢',
    '▢ • */loja*',
    '▢   ⤷ Mostra os itens e melhorias disponíveis.',
    '▢',
    '▢ • */comprar Ki*',
    '▢   ⤷ Compra o próximo nível de Ki.',
    '▢',
    '▢ • */comprar item*',
    '▢   ⤷ Compra um item da loja.',
    '▢',
    '▢ • */inventario*',
    '▢   ⤷ Lista seus itens comprados.',
    '▢',
    '╰━━─「💰」─━━',
    '',

    '╭━━⪩ ⚡ *KI & PROGRESSÃO* ⪨━━',
    '▢',
    '▢ • Cada nível de Ki aumenta seus atributos totais.',
    '▢ • Cada Ki concede +4.000.000 em atributos.',
    '▢',
    '▢ • Exemplo:',
    '▢   ⤷ Ki 01 = 4.000.000 atributos',
    '▢   ⤷ Ki 05 = 20.000.000 atributos',
    '▢',
    '▢ • Use */comprar Ki* para evoluir.',
    '▢',
    '╰━━─「⚡」─━━',
    '',

    '╭━━⪩ 🎯 *EVENTOS DIÁRIOS* ⪨━━',
    '▢',
    '▢ • */eventos*',
    '▢   ⤷ Mostra eventos e seu limite diário.',
    '▢',
    '▢ • */eventos pergunta*',
    '▢   ⤷ Responda uma pergunta de Dragon Ball.',
    '▢',
    '▢ • */eventos forca*',
    '▢   ⤷ Inicia uma forca temática.',
    '▢',
    '▢ • */eventos desafio*',
    '▢   ⤷ Recebe um desafio rápido do RPG.',
    '▢',
    '▢ • */responder A*',
    '▢   ⤷ Responde pergunta ou desafio ativo.',
    '▢',
    '▢ • */letra A*',
    '▢   ⤷ Tenta uma letra na forca.',
    '▢',
    '▢ • */chutar palavra*',
    '▢   ⤷ Tenta finalizar a forca.',
    '▢',
    '▢ • */pegar*',
    '▢   ⤷ Pega o emoji do dragão quando aparecer.',
    '▢',
    '╰━━─「🎯」─━━',
    '',

    '╭━━⪩ 🎰 *CASSINO DRAGONVERSE* ⪨━━',
    '▢',
    '▢ • */tigrinho valor*',
    '▢   ⤷ Caça-níquel com 🐉 🐯 🦍 💎 ⭐ 🔥 🍀 🪙 💩.',
    '▢',
    '▢ • */blackjack iniciar valor*',
    '▢   ⤷ Joga Blackjack contra a mesa.',
    '▢',
    '▢ • */blackjack carta* | */blackjack parar* | */blackjack dobrar*',
    '▢   ⤷ Controla sua mão no Blackjack.',
    '▢',
    '▢ • Aposta mínima geral:',
    '▢   ⤷ 1.000.000 Zenies.',
    '▢',
    '╰━━─「🎰」─━━',
    '',

    '╭━━⪩ ♠️ *JOGOS DE CARTAS* ⪨━━',
    '▢',
    '▢ • */poker criar valor*',
    '▢   ⤷ Cria mesa de Poker Texas Hold’em.',
    '▢',
    '▢ • */poker entrar* | */poker iniciar*',
    '▢   ⤷ Entra na mesa e inicia a mão.',
    '▢',
    '▢ • */check* ou */poker check*',
    '▢   ⤷ Passa a vez quando ninguém apostou acima de você.',
    '▢',
    '▢ • */cobrir* ou */poker cobrir*',
    '▢   ⤷ Cobre a aposta atual da rodada.',
    '▢',
    '▢ • */poker apostar valor*',
    '▢   ⤷ Aposta ou aumenta para esse valor na rodada.',
    '▢',
    '▢ • */poker allin* ou */allin*',
    '▢   ⤷ Coloca todos seus Zenies disponíveis na mão.',
    '▢',
    '▢ • */out* ou */poker out*',
    '▢   ⤷ Desiste da mão.',
    '▢',
    '▢ • */pote* ou */poker pote*',
    '▢   ⤷ Mostra pote, mesa, apostas e vez atual.',
    '▢',
    '▢ • */sair* ou */poker sair*',
    '▢   ⤷ Sai antes do início; durante a mão, conta como /out.',
    '▢',
    '▢ • */poker cartas*',
    '▢   ⤷ Reenvia suas cartas no privado.',
    '▢',
    '▢ • O Poker agora avança automaticamente quando todos dão check, cobrem, apostam ou saem.',
    '▢ • Potes paralelos devolvem excedentes para o dono original.',
    '▢',
    '▢ • */truco criar* | */truco entrar* | */truco iniciar*',
    '▢   ⤷ Cria e inicia Truco Paulista limpo.',
    '▢',
    '▢ • */truco jogar 1*',
    '▢   ⤷ Joga uma carta enviada no privado.',
    '▢',
    '▢ • */truco truco* | */truco seis* | */truco nove* | */truco doze*',
    '▢   ⤷ Aumenta o valor da mão.',
    '▢',
    '╰━━─「♠️」─━━',
    '',

    '╭━━⪩ 👑 *CARGOS & HIERARQUIA* ⪨━━',
    '▢',
    '▢ • */cargos*',
    '▢   ⤷ Mostra IDs de cargos e trabalhos.',
    '▢',
    '▢ • Cargos Supremos:',
    '▢   ⤷ Autoridade Suprema',
    '▢   ⤷ Supremo Ministro',
    '▢   ⤷ Hakaishin',
    '▢   ⤷ Anjo',
    '▢   ⤷ Grande Kaioshin',
    '▢',
    '▢ • Cargos supremos pertencem à Alta Cúpula.',
    '▢ • Eles não ocupam personagem comum do universo.',
    '▢',
    '╰━━─「👑」─━━',
    '',

    '╭━━⪩ 🛡️ *ADMIN / ALTA CÚPULA* ⪨━━',
    '▢',
    '▢ • */codigoresgate personagem*',
    '▢   ⤷ Gera código para personagem bloqueado.',
    '▢',
    '▢ • */addzenies @pessoa valor*',
    '▢   ⤷ Adiciona Zenies ao jogador.',
    '▢',
    '▢ • */retirarzenies @pessoa valor*',
    '▢   ⤷ Remove Zenies do jogador.',
    '▢',
    '▢ • */definirki @pessoa valor*',
    '▢   ⤷ Define o Ki de um jogador.',
    '▢',
    '▢ • */adduniverso número*',
    '▢   ⤷ Cria um novo universo limpo.',
    '▢',
    '▢ • */addpersonagem Nome Block*',
    '▢   ⤷ Adiciona personagem bloqueado.',
    '▢',
    '▢ • */addpersonagem Nome Free*',
    '▢   ⤷ Adiciona personagem livre.',
    '▢',
    '▢ • */rmvpersonagem Nome*',
    '▢   ⤷ Remove personagem da lista.',
    '▢',
    '▢ • */addcargo @pessoa ID*',
    '▢   ⤷ Adiciona cargo ou trabalho.',
    '▢',
    '▢ • */eventos ativar*',
    '▢   ⤷ Ativa eventos automáticos no chat.',
    '▢',
    '▢ • */eventos desativar*',
    '▢   ⤷ Desativa eventos automáticos no chat.',
    '▢',
    '╰━━─「🛡️」─━━',
    '',

    '╭━━⪩ 🐲 *DRAGONVERSE* ⪨━━',
    '▢',
    '▢ • Treine.',
    '▢ • Evolua seu Ki.',
    '▢ • Proteja seu universo.',
    '▢ • Supere seus limites.',
    '▢',
    '╰━━─「🐲」─━━',
  ].join('\n'));
}

module.exports = { helpCommand };
