function getBrazilDateTime() {
  const now = new Date();

  const date = now.toLocaleDateString('pt-BR', {
    timeZone: 'America/Campo_Grande',
  });

  const time = now.toLocaleTimeString('pt-BR', {
    timeZone: 'America/Campo_Grande',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  return { date, time };
}

async function helpCommand(message) {
  const { date, time } = getBrazilDateTime();

  await message.reply([
    '╭━━⪩ 🐉 *DRAGONVERSE BOT* ⪨━━',
    '▢',
    '▢ • *RPG:* DragonVerse',
    `▢ • *Data:* ${date}`,
    `▢ • *Hora:* ${time}`,
    '▢ • *Prefixo:* /',
    '▢ • *Versão:* 1.9.0',
    '▢ • *Menu:* /menu',
    '▢',
    '╰━━─「🪐」─━━',
    '',

    '╭━━⪩ 👤 *REGISTRO & PERFIL* ⪨━━',
    '▢',
    '▢ • */Personagens Nº*',
    '▢   ⤷ Mostra a lista de personagens do universo do numero.',
    '▢',
    '▢ • */Registro 2 PP*',
    '▢   ⤷ Registra um personagem livre.',
    '▢',
    '▢ • */Registro 2 PPBLOCK CÓDIGO*',
    '▢   ⤷ Registra personagem bloqueado com código.',
    '▢',
    '▢ • */Trocarpersonagem PP*',
    '▢   ⤷ Troca seu personagem por outro livre.',
    '▢   ⤷ Custo: 25% dos seus Zenies.',
    '▢   ⤷ Para bloqueado: use código de /codigoresgate.',
    '▢',
    '▢ • */Perfil*',
    '▢   ⤷ Mostra personagem, Ki, Zenies, cargo e trabalho.',
    '▢',
    '▢ • */meuid*',
    '▢   ⤷ Mostra seu JID/LID para virar admin.',
    '▢',
    '╰━━─「👤」─━━',
    '',

    '╭━━⪩ 💰 *ECONOMIA & BANCO* ⪨━━',
    '▢',
    '▢ • */depositar valor*',
    '▢   ⤷ Deposita Zenies no banco.',
    '▢   ⤷ Rende 25% a cada 4 dias.',
    '▢',
    '▢ • */saldo*',
    '▢   ⤷ Mostra só seus Zenies e dados da poupança.',
    '▢',
    '▢ • */retirarpoupanca valor*',
    '▢   ⤷ Retira Zenies da poupança/depósito.',
    '▢',
    '▢ • */pix @pessoa valor*',
    '▢   ⤷ Transfere Zenies para outro jogador.',
    '▢',
    '▢ • */extrato*',
    '▢   ⤷ Mostra entradas, saídas, perdas, PIX e compras.',
    '▢',
    '▢ • */extrato entrada* | */extrato saida* | */extrato perda*',
    '▢   ⤷ Filtra seu histórico financeiro.',
    '▢',
    '▢ • */loja*',
    '▢   ⤷ Mostra os itens e melhorias disponíveis.',
    '▢',
    '▢ • */comprar Ki*',
    '▢   ⤷ Compra o próximo nível de Ki.',
    '▢',
    '▢ • */comprar item*',
    '▢   ⤷ Compra um item da loja.',
    '▢',
    '▢ • */inventario*',
    '▢   ⤷ Lista seus itens comprados.',
    '▢',
    '▢ • */emprestimo status*',
    '▢   ⤷ Mostra empréstimo/dívida ativa.',
    '▢',
    '▢ • */emprestimo aceitar* | */emprestimo recusar*',
    '▢   ⤷ Responde oferta quando seu saldo fica negativo.',
    '▢',
    '▢ • */emprestimo pagar valor*',
    '▢   ⤷ Paga uma dívida ativa.',
    '▢',
    '▢ • */convite gerar*',
    '▢   ⤷ Gera seu código de convite.',
    '▢',
    '▢ • */convite usar CODIGO*',
    '▢   ⤷ Usa código de convite nas primeiras 5 horas.',
    '▢',
    '╰━━─「💰」─━━',
    '',

    '╭━━⪩ ⚡ *KI & PROGRESSÃO* ⪨━━',
    '▢',
    '▢ • Cada nível de Ki aumenta seus atributos totais.',
    '▢ • Cada Ki concede +4.000.000 em atributos.',
    '▢',
    '▢ • Exemplo:',
    '▢   ⤷ Ki 01 = 4.000.000 atributos',
    '▢   ⤷ Ki 05 = 20.000.000 atributos',
    '▢',
    '▢ • Use */comprar Ki* para evoluir.',
    '▢',
    '╰━━─「⚡」─━━',
    '',

    '╭━━⪩ 🎯 *EVENTOS DIÁRIOS* ⪨━━',
    '▢',
    '▢ • */eventos*',
    '▢   ⤷ Mostra eventos e seu limite diário.',
    '▢',
    '▢ • */eventos pergunta*',
    '▢   ⤷ Responda uma pergunta de Dragon Ball.',
    '▢',
    '▢ • */eventos forca*',
    '▢   ⤷ Inicia uma forca temática.',
    '▢',
    '▢ • */eventos desafio*',
    '▢   ⤷ Recebe um desafio rápido do RPG.',
    '▢',
    '▢ • */responder A*',
    '▢   ⤷ Responde pergunta ou desafio ativo.',
    '▢',
    '▢ • */letra A*',
    '▢   ⤷ Tenta uma letra na forca.',
    '▢',
    '▢ • */chutar palavra*',
    '▢   ⤷ Tenta finalizar a forca.',
    '▢',
    '▢ • */pegar*',
    '▢   ⤷ Pega o emoji do dragão quando aparecer.',
    '▢   ⤷ Recompensa atual: 50.000.000 Zenies.',
    '▢',
    '▢ • */presenca*',
    '▢   ⤷ Marca presença e conta streak.',
    '▢',
    '▢ • */rankeventos diario* | */rankeventos semanal*',
    '▢   ⤷ Mostra ranking de eventos.',
    '▢',
    '▢ • Eventos manuais: 50.000.000 por acerto, limite de 10 por dia.',
    '▢ • Pergunta relâmpago: 100.000.000, 1 tentativa por pessoa.',
    '▢ • Automáticos só aparecem das 05:00 até 00:00.',
    '▢',
    '▢ • */caixa* | */caixa abrir 10kk*',
    '▢   ⤷ Abre caixas com Zenies e colecionáveis.',
    '▢   ⤷ Limite: 10 caixas por dia.',
    '▢   ⤷ Recompensa ponderada: 18% não vem dinheiro; até 4x no prêmio máximo.',
    '▢',
    '╰━━─「🎯」─━━',
    '',

    '╭━━⪩ 🎰 *CASSINO DRAGONVERSE* ⪨━━',
    '▢',
    '▢ • */tigrinho valor*',
    '▢   ⤷ Caça-níquel rebalanceado com 🐉 🐯 🦍 💎 ⭐ 🔥 🍀 🪙 💩.',
    '▢   ⤷ Coco faz perder o dobro e pode deixar negativo.',
    '▢',
    '▢ • */blackjack criar valor*',
    '▢   ⤷ Cria mesa de Blackjack.',
    '▢',
    '▢ • */blackjack entrar* | */blackjack start*',
    '▢   ⤷ Entra e inicia a mesa.',
    '▢',
    '▢ • */carta* | */parar*',
    '▢   ⤷ Pede carta ou para na sua vez.',
    '▢',
    '▢ • Aposta mínima geral:',
    '▢   ⤷ 1.000.000 Zenies.',
    '▢',
    '╰━━─「🎰」─━━',
    '',

    '╭━━⪩ ♠️ *JOGOS DE CARTAS* ⪨━━',
    '▢',
    '▢ • */poker criar valor*',
    '▢   ⤷ Cria mesa de Poker Texas Hold’em.',
    '▢',
    '▢ • */poker entrar*',
    '▢   ⤷ Entra na mesa pagando a entrada.',
    '▢',
    '▢ • */poker iniciar*',
    '▢   ⤷ O bot manda as cartas no privado.',
    '▢',
    '▢ • */check* | */poker check*',
    '▢   ⤷ Passa a vez quando ninguém apostou.',
    '▢',
    '▢ • */cobrir* | */poker cobrir*',
    '▢   ⤷ Cobre a aposta atual.',
    '▢',
    '▢ • */poker apostar valor*',
    '▢   ⤷ Aposta ou aumenta a rodada.',
    '▢',
    '▢ • */allin* | */poker allin*',
    '▢   ⤷ Coloca todos seus Zenies disponíveis na mão.',
    '▢',
    '▢ • */out* | */poker out*',
    '▢   ⤷ Desiste da mão.',
    '▢',
    '▢ • */pote* | */poker pote*',
    '▢   ⤷ Mostra pote, mesa, jogadores e vez atual.',
    '▢',
    '▢ • Avanço automático:',
    '▢   ⤷ Quando todos agirem, o bot abre flop/turn/river sozinho.',
    '▢',
    '▢ • */truco criar valor* | */truco entrar* | */truco iniciar*',
    '▢   ⤷ Cria e inicia Truco Paulista sujo com aposta.',
    '▢',
    '▢ • */Ltruco criar valor* | */Ltruco entrar* | */Ltruco iniciar*',
    '▢   ⤷ Cria Truco limpo: cartas 3,2,A,K,J,Q, com vira e manilha.',
    '▢',
    '▢ • */truco jogar 1*',
    '▢   ⤷ Joga uma carta enviada no privado.',
    '▢',
    '▢ • */3* | */6* | */9* | */12*',
    '▢   ⤷ Pede aumento na sua vez.',
    '▢',
    '▢ • */aceitar* | */recusar*',
    '▢   ⤷ Responde pedido de truco/aumento quando o bot marcar você.',
    '▢',
    '▢ • */regras poker* | */regras blackjack* | */regras truco*',
    '▢   ⤷ Mostra as regras e combinações dos jogos.',
    '▢',
    '╰━━─「♠️」─━━',
    '',


    '╭━━⪩ ⚔️ *RANKEADA & Z MARKET* ⪨━━',
    '▢',
    '▢ • */Rankeada*',
    '▢   ⤷ Explica regras, PR, PC, elos e comandos.',
    '▢',
    '▢ • */iRank*',
    '▢   ⤷ Inscreve você na lista rankeada.',
    '▢',
    '▢ • */listaRank*',
    '▢   ⤷ Mostra todos os inscritos com personagem, PR e PC.',
    '▢',
    '▢ • */Desafio @pessoa*',
    '▢   ⤷ Desafia alguém inscrito na lista rankeada e gera ID de luta.',
    '▢   ⤷ Disponível somente das 06:00 às 22:00.',
    '▢   ⤷ W.O pausa das 23:00 às 06:00.',
    '▢',
    '▢ • */Adesafio* | */Rdesafio*',
    '▢   ⤷ Aceita ou recusa desafio pendente.',
    '▢',
    '▢ • */RV ID @vencedor*',
    '▢   ⤷ ADM/Alta Cúpula/Juiz Oficial registra vencedor.',
    '▢',
    '▢ • */removerrank @pessoa*',
    '▢   ⤷ ADM/Alta Cúpula remove alguém da lista rankeada.',
    '▢',
    '▢ • */ZMarket*',
    '▢   ⤷ Mostra habilidades e auxiliares compráveis com PC.',
    '▢',
    '▢ • */Zbuy nome*',
    '▢   ⤷ Compra habilidade ou auxiliar com PC.',
    '▢',
    '╰━━─「⚔️」─━━',
    '',
    
    '╭━━⪩ 🌌 VIAGEM ENTRE UNIVERSOS ⪨━━',
    '▢ /linkar universo',
    '▢ /viajar universo',
    '▢ custo 50kk | 24h retorno',
    '╰━━─',
    '',

    '╭━━⪩ 🔇 CONTROLE ⪨━━',
    '▢ /mute @user',
    '▢ /unmute @user',
    '▢ /blockcmd comando',
    '▢ /unblockcmd comando',
    '╰━━─',
    '',
    
    '╭━━⪩ 🏆 *TORNEIOS* ⪨━━',
    '▢',
    '▢ • */gerartorneio Nome Valor*',
    '▢   ⤷ ADM/Alta Cúpula cria torneio com inscrição.',
    '▢',
    '▢ • */inscrever torneio* ou */inscrever Nome*',
    '▢   ⤷ Entra no torneio aberto do grupo.',
    '▢',
    '▢ • */torneio iniciar*',
    '▢   ⤷ Inicia e gera a chave do torneio.',
    '▢',
    '▢ • */torneio*',
    '▢   ⤷ Mostra a chave atual.',
    '▢',
    '▢ • */vencedor NºDaLuta @pessoa*',
    '▢   ⤷ ADM/Alta Cúpula registra vencedor e avança fase.',
    '▢',
    '╰━━─「🏆」─━━',
    '',
    '╭━━⪩ 👑 *CARGOS & HIERARQUIA* ⪨━━',
    '▢',
    '▢ • */cargos*',
    '▢   ⤷ Mostra IDs de cargos e trabalhos.',
    '▢',
    '▢ • Cargos Supremos:',
    '▢   ⤷ Autoridade Suprema',
    '▢   ⤷ Supremo Ministro',
    '▢   ⤷ Hakaishin',
    '▢   ⤷ Anjo',
    '▢   ⤷ Grande Kaioshin',
    '▢',
    '▢ • Cargos supremos pertencem à Alta Cúpula.',
    '▢ • Eles não ocupam personagem comum do universo.',
    '▢',
    '╰━━─「👑」─━━',
    '',

    '╭━━⪩ 🛡️ *ADMIN / ALTA CÚPULA* ⪨━━',
    '▢',
    '▢ • */codigoresgate personagem*',
    '▢   ⤷ Gera código universal para personagem bloqueado.',
    '▢',
    '▢ • */codigoresgate 2 personagem*',
    '▢   ⤷ Gera código válido somente no Universo 2.',
    '▢',
    '▢ • */codes tipo valor quantidade*',
    '▢   ⤷ Cria code de desconto, Zenies ou Ki.',
    '▢   ⤷ Desconto vale somente na próxima compra.',
    '▢',
    '▢ • */inspecionar CODIGO*',
    '▢   ⤷ Inspeciona códigos de /codigoresgate e /codes.',
    '▢',
    '▢ • */deleteplayer número*',
    '▢   ⤷ Deleta totalmente o player da lista /players.',
    '▢',
    '▢ • */addzenies @pessoa valor*',
    '▢   ⤷ Adiciona Zenies ao jogador.',
    '▢',
    '▢ • */retirarzenies @pessoa valor*',
    '▢   ⤷ Remove Zenies do jogador.',
    '▢',
    '▢ • */definirki @pessoa valor*',
    '▢   ⤷ Define o Ki de um jogador.',
    '▢',
    '▢ • */adduniverso número*',
    '▢   ⤷ Cria um novo universo limpo.',
    '▢',
    '▢ • */addpersonagem Nome Block*',
    '▢   ⤷ Adiciona personagem bloqueado em todos os universos.',
    '▢',
    '▢ • */addpersonagem Nome Free*',
    '▢   ⤷ Adiciona personagem livre em todos os universos.',
    '▢',
    '▢ • */rmvpersonagem Nome*',
    '▢   ⤷ Remove personagem de todos os universos.',
    '▢',
    '▢ • */addcargo @pessoa ID*',
    '▢   ⤷ Adiciona cargo ou trabalho.',
    '▢',
    '▢ • */eventos ativar*',
    '▢   ⤷ Ativa eventos automáticos no chat.',
    '▢',
    '▢ • */eventos desativar*',
    '▢   ⤷ Desativa eventos automáticos no chat.',
    '▢',
    '╰━━─「🛡️」─━━',
    '',

    '╭━━⪩ 🐲 *DRAGONVERSE* ⪨━━',
    '▢',
    '▢ • Treine.',
    '▢ • Evolua seu Ki.',
    '▢ • Proteja seu universo.',
    '▢ • Supere seus limites.',
    '▢',
    '╰━━─「🐲」─━━',
  ].join('\n'));
}

module.exports = { helpCommand };

