function formatDateTime() {
  const now = new Date();

  const date = now.toLocaleDateString('pt-BR', {
    timeZone: 'America/Campo_Grande',
  });

  const time = now.toLocaleTimeString('pt-BR', {
    timeZone: 'America/Campo_Grande',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  return { date, time };
}

async function helpCommand(message) {
  const { date, time } = formatDateTime();

  await message.reply([
    '╭━━⪩ 🐉 DRAGONVERSE BOT ⪨━━',
    '▢',
    '▢ • RPG: DragonVerse',
    `▢ • Data: ${date}`,
    `▢ • Hora: ${time}`,
    '▢ • Prefixo: /',
    '▢ • Versão: 1.0.0',
    '▢ • Sistema: WhatsApp RPG',
    '▢',
    '╰━━─「🪐」─━━',
    '',
    '╭━━⪩ 👤 REGISTRO & PERFIL ⪨━━',
    '▢',
    '▢ • /Personagens Nº',
    '▢   ↳ Mostra a lista de personagens do universo do numero.',
    '▢',
    '▢ • /Registro 2 PPLIVRE',
    '▢   ↳ Registra um personagem livre no universo do numero.',
    '▢',
    '▢ • /Registro 2 PPBLOCK CÓDIGO',
    '▢   ↳ Registra personagem bloqueado usando código.',
    '▢',
    '▢ • /Trocarpersonagem PP',
    '▢   ↳ Troca seu personagem por outro livre.',
    '▢   ↳ Custo: 25% dos seus Zenies.',
    '▢',
    '▢ • /Perfil',
    '▢   ↳ Mostra seu personagem, Ki, Zenies, cargo e progresso.',
    '▢',
    '▢ • /meuid',
    '▢   ↳ Mostra seu JID/LID/número para virar admin.',
    '▢',
    '╰━━─「👤」─━━',
    '',
    '╭━━⪩ 💰 ECONOMIA & BANCO ⪨━━',
    '▢',
    '▢ • /depositar valor',
    '▢   ↳ Deposita Zenies no banco.',
    '▢   ↳ Rende 25% a cada 4 dias.',
    '▢',
    '▢ • /transferir @pessoa valor',
    '▢   ↳ Transfere Zenies para outro jogador.',
    '▢',
    '▢ • /loja',
    '▢   ↳ Mostra a loja do DragonVerse.',
    '▢',
    '▢ • /comprar Ki',
    '▢   ↳ Compra o próximo nível de Ki.',
    '▢',
    '▢ • /comprar item',
    '▢   ↳ Compra um item da loja.',
    '▢',
    '▢ • /inventario',
    '▢   ↳ Lista todos os seus itens comprados.',
    '▢',
    '╰━━─「💰」─━━',
    '',
    '╭━━⪩ 🔥 KI & PODER ⪨━━',
    '▢',
    '▢ • Todo jogador começa com Ki 01.',
    '▢ • Cada nível de Ki adiciona:',
    '▢   ↳ +4.000.000 em atributos totais.',
    '▢',
    '▢ • Ki 01 = 4.000.000 atributos',
    '▢ • Ki 02 = 8.000.000 atributos',
    '▢ • Ki 03 = 12.000.000 atributos',
    '▢',
    '▢ • Use /comprar Ki para evoluir.',
    '▢',
    '╰━━─「🔥」─━━',
    '',
    '╭━━⪩ 🎯 EVENTOS DIÁRIOS ⪨━━',
    '▢',
    '▢ • /eventos',
    '▢   ↳ Mostra eventos e seu limite diário.',
    '▢',
    '▢ • /eventos pergunta',
    '▢   ↳ Recebe uma pergunta de Dragon Ball.',
    '▢',
    '▢ • /eventos forca',
    '▢   ↳ Inicia uma forca temática.',
    '▢',
    '▢ • /eventos desafio',
    '▢   ↳ Inicia um desafio rápido.',
    '▢',
    '▢ • /responder A',
    '▢   ↳ Responde perguntas e desafios.',
    '▢',
    '▢ • /letra A',
    '▢   ↳ Tenta uma letra na forca.',
    '▢',
    '▢ • /chutar palavra',
    '▢   ↳ Tenta finalizar a forca.',
    '▢',
    '▢ • /pegar',
    '▢   ↳ Pega o emoji do dragão quando aparecer.',
    '▢',
    '▢ • Limite manual:',
    '▢   ↳ 10 eventos por dia.',
    '▢   ↳ 10.000.000 Zenies por acerto.',
    '▢   ↳ Máximo: 100.000.000 Zenies por dia.',
    '▢',
    '╰━━─「🎯」─━━',
    '',
    '╭━━⪩ 🎰 CASSINO DRAGONVERSE ⪨━━',
    '▢',
    '▢ • /tigrinho valor',
    '▢   ↳ Joga o caça-níquel do DragonVerse.',
    '▢',
    '▢ • Aposta mínima:',
    '▢   ↳ 1.000.000 Zenies.',
    '▢',
    '▢ • Limite:',
    '▢   ↳ 3 apostas por dia.',
    '▢',
    '▢ • Símbolos especiais:',
    '▢   ↳ 🐉 Dragão',
    '▢   ↳ 🐯 Tigre',
    '▢   ↳ 🦍 Gorila',
    '▢   ↳ 💎 Diamante',
    '▢   ↳ 🍀 Trevo',
    '▢   ↳ 💩 Azar absoluto',
    '▢',
    '▢ • 3 💩 ou mais:',
    '▢   ↳ Perde o dobro da aposta.',
    '▢',
    '╰━━─「🎰」─━━',
    '',
    '╭━━⪩ 👑 CARGOS & HIERARQUIA ⪨━━',
    '▢',
    '▢ • /cargos',
    '▢   ↳ Mostra os IDs dos cargos disponíveis.',
    '▢',
    '▢ • Cargos Supremos:',
    '▢   ↳ Autoridade Suprema',
    '▢   ↳ Supremo Ministro',
    '▢   ↳ Hakaishin',
    '▢   ↳ Anjo',
    '▢   ↳ Grande Kaioshin',
    '▢',
    '▢ • Cargos supremos pertencem à Alta Cúpula.',
    '▢ • Eles não ocupam personagem comum do universo.',
    '▢',
    '╰━━─「👑」─━━',
    '',
    '╭━━⪩ 🛡️ ADMIN / ALTA CÚPULA ⪨━━',
    '▢',
    '▢ • /codigoresgate personagem',
    '▢   ↳ Gera código para personagem bloqueado.',
    '▢',
    '▢ • /addzenies @pessoa valor',
    '▢   ↳ Adiciona Zenies ao jogador.',
    '▢',
    '▢ • /retirarzenies @pessoa valor',
    '▢   ↳ Remove Zenies do jogador.',
    '▢',
    '▢ • /definirki @pessoa valor',
    '▢   ↳ Define o Ki do jogador.',
    '▢',
    '▢ • /adduniverso número',
    '▢   ↳ Cria um novo universo.',
    '▢',
    '▢ • /addpersonagem Nome Block',
    '▢   ↳ Adiciona personagem bloqueado.',
    '▢',
    '▢ • /addpersonagem Nome Free',
    '▢   ↳ Adiciona personagem livre.',
    '▢',
    '▢ • /rmvpersonagem Nome',
    '▢   ↳ Remove personagem da lista.',
    '▢',
    '▢ • /addcargo @pessoa ID',
    '▢   ↳ Adiciona cargo ou trabalho ao jogador.',
    '▢',
    '▢ • /eventos ativar',
    '▢   ↳ Ativa eventos automáticos no grupo.',
    '▢',
    '▢ • /eventos desativar',
    '▢   ↳ Desativa eventos automáticos no grupo.',
    '▢',
    '╰━━─「🛡️」─━━',
    '',
    '╭━━⪩ 🐲 DRAGONVERSE ⪨━━',
    '▢',
    '▢ • Escolha seu personagem.',
    '▢ • Treine seu Ki.',
    '▢ • Ganhe Zenies.',
    '▢ • Participe dos eventos.',
    '▢ • Suba na hierarquia.',
    '▢ • Proteja seu universo.',
    '▢',
    '╰━━─「🐉」─━━',
  ].join('\n'));
}

module.exports = { helpCommand };
